version: "3"

services:
  postgres:
    container_name: aestivius_postgres_container
    image: postgres:alpine
    environment:
      - POSTGRES_USER=aestivius
      - POSTGRES_PASSWORD=aestiviuspassword
      - PGDATA=/data/postgres
    volumes:
      - /var/lib/aestivius/docker_postgres1:/data/postgres
      - ./fill_db.sql:/docker-entrypoint-initdb.d/init.sql
    #ports:
    #  - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  server:
    container_name: aestivius_container
    image: speedphoenix/aestivius-db-server
    environment:
      - PGHOST=postgres
      - PGUSER=aestivius
      - PGDATABASE=aestivius
      - PGPASSWORD=aestiviuspassword
    ports:
      - "32768:8096"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
