version: "3"

services:
  postgres:
    container_name: postgres_container
    image: postgres:alpine
    environment:
      - POSTGRES_USER=aestivius
      - POSTGRES_PASSWORD=aestiviuspassword
    volumes:
      - /tmp/docker_postgres1:/data/postgres
      - ./fill_db.sql:/docker-entrypoint-initdb.d/init.sql
    #ports:
    #  - "5432:5432"
    networks:
      - postgres

  server:
    container_name: aestivius_container
    image: speedphoenix/aestivius-db-server
    environment:
      - PGHOST=postgres
      - PGUSER=aestivius
      - PGDATABASE=aestivius
      - PGPASSWORD=aestiviuspassword
    ports:
      - "8096:8096"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
